#!/usr/bin/env python
from misc.utility.scons_hints import *

import os

Import("env")

env_streamline = env.Clone()
env_streamline.Prepend(CPPPATH=["#thirdparty/vulkan/include"])

streamline_path = env.get("streamline_sdk_path", "")
if streamline_path and os.path.isdir(streamline_path):
    include_path = os.path.join(streamline_path, "include")
    if os.path.isdir(include_path):
        env_streamline.Prepend(CPPPATH=[include_path])
        env_streamline.AppendUnique(CPPDEFINES=["STREAMLINE_SDK_HEADERS_PRESENT"])
    elif os.path.isfile(os.path.join(streamline_path, "sl.h")):
        env_streamline.Prepend(CPPPATH=[streamline_path])
        env_streamline.AppendUnique(CPPDEFINES=["STREAMLINE_SDK_HEADERS_PRESENT"])

streamline_obj = []
env_streamline.add_source_files(streamline_obj, "*.cpp")
env.drivers_sources += streamline_obj
