#!/usr/bin/env python
from misc.utility.scons_hints import *

import methods

Import("env")
Import("env_modules")

env_etcpak = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []

thirdparty_dir = "#thirdparty/etcpak/"
thirdparty_sources = [
    "DecodeRGB.cpp",
    "Dither.cpp",
    "ProcessDxtc.cpp",
    "ProcessRGB.cpp",
    "Tables.cpp",
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_etcpak.Prepend(CPPPATH=[thirdparty_dir])

env_thirdparty = env_etcpak.Clone()
if env["arch"] == "x86_64" and env.msvc and not methods.using_clang(env):
    # MSVC's /arch:AVX2 build does not expose the full set of GNU-style
    # feature macros ETCpak uses to keep its AVX2 and SSE4.1 tables in sync.
    env_thirdparty.AppendUnique(
        CPPDEFINES=[
            "__SSE__",
            "__SSE2__",
            "__SSE3__",
            "__SSSE3__",
            "__SSE4_1__",
            "__SSE4_2__",
            "__AVX__",
            "__AVX2__",
            "__FMA__",
        ]
    )
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

# Godot source files

module_obj = []

env_etcpak.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
