#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

from pathlib import Path

import platform_linuxbsd_builders

sources = []

common_linuxbsd = [
    "crash_handler_linuxbsd.cpp",
    "os_linuxbsd.cpp",
    "freedesktop_portal_desktop.cpp",
    "freedesktop_screensaver.cpp",
    "freedesktop_at_spi_monitor.cpp",
]

if env["library_type"] == "executable":
    common_linuxbsd += ["godot_linuxbsd_main.cpp"]
    if env["arch"] == "x86_64":
        env_cpu_check = env.Clone()
        env_cpu_check.add_source_files(sources, ["godot_linuxbsd.cpp"])
        for flag in env.get("faster_godot_gnu_x86_isa_flags", []):
            if flag in env_cpu_check["CCFLAGS"]:
                env_cpu_check["CCFLAGS"].remove(flag)
    else:
        common_linuxbsd += ["godot_linuxbsd.cpp"]
else:
    common_linuxbsd += ["libgodot_linuxbsd.cpp"]

if env["use_sowrap"]:
    common_linuxbsd.append("xkbcommon-so_wrap.c")

if env["x11"]:
    common_linuxbsd += SConscript("x11/SCsub")

if env["wayland"]:
    common_linuxbsd += SConscript("wayland/SCsub")

if env["speechd"]:
    common_linuxbsd.append("tts_linux.cpp")
    if env["use_sowrap"]:
        common_linuxbsd.append("speechd-so_wrap.c")

if env["fontconfig"]:
    if env["use_sowrap"]:
        common_linuxbsd.append("fontconfig-so_wrap.c")

if env["dbus"]:
    if env["use_sowrap"]:
        common_linuxbsd.append("dbus-so_wrap.c")

program_name = "#bin/faster-godot"

if env["library_type"] == "static_library":
    prog = env.add_library(program_name, common_linuxbsd + sources)
elif env["library_type"] == "shared_library":
    prog = env.add_shared_library(program_name, common_linuxbsd + sources)
else:
    prog = env.add_program(program_name, common_linuxbsd + sources)


def stage_vendor_upscaler_runtime_libs(prog):
    runtime_libs = env.get("vendor_upscaler_runtime_libs", [])
    if not runtime_libs:
        return []

    staged_libs = []
    staged_names = set()
    for runtime_lib in runtime_libs:
        runtime_lib_path = Path(runtime_lib)
        runtime_lib_name = runtime_lib_path.name
        if runtime_lib_name in staged_names:
            continue

        staged_names.add(runtime_lib_name)
        staged_lib = env.CommandNoCache(f"#bin/{runtime_lib_name}", str(runtime_lib_path), Copy("$TARGET", "$SOURCE"))
        env.Depends(prog, staged_lib)
        Clean(prog, staged_lib)
        staged_libs += staged_lib

    return staged_libs


stage_vendor_upscaler_runtime_libs(prog)

if env["debug_symbols"] and env["separate_debug_symbols"]:
    env.AddPostAction(prog, env.Run(platform_linuxbsd_builders.make_debug_linuxbsd))
